mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.oa.platform.entity
  configuration: # mybatis全局配置
    cache-enabled: true
    local-cache-scope: session

logging:
  level:
    com:
      oa:
        platform:
          repository: debug

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

#二维码相关设置
qrcode:
  width: 400
  height: 400
  dirName: qrcode
  suffix: png

platform:
  session-keys:
    user: OA-PLATFORM-SYSTEM-MANAGE-USER

spring:
  profiles:
    active: prod
