mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.oa.platform.entity
  configuration: # mybatis全局配置
    cache-enabled: true
    local-cache-scope: session

logging:
  level:
    web: DEBUG
    com:
      oa:
        platform:
          repository: debug

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

platform:
  session-keys:
    user: OA-PLATFORM-SYSTEM-MANAGE-USER

spring:
  profiles:
    active: prod
